### ISSUE TITLE
Ask for the code

### ISSUE THREAD

**Issue by xiaolan98** [Lancelot39/KGSF#1]
Is there any progress in the code of KGSF uploading?

**Comment by Lancelot39** [comment]
> Is there any progress in the code of KGSF uploading?

Thanks for your attention, I am now preparing the code, I am sure that the code will be public before 8.22

**Comment by xiaolan98** [comment]
Thank you very much. I'll wait for you to upload.

**Comment by xiaolan98** [comment]
Is there any progress?

**Comment by Lancelot39** [comment]
> Is there any progress?

Thanks for your patient, I just upload all the code and affiliated files, to make sure that everyone can train this model by one line code.
