### ISSUE TITLE
Access denied of word2vec_redial.npy

### ISSUE THREAD

**Issue by mushroomhe** [Lancelot39/KGSF#4]
您好，我想请问一下word2vec_redial.npy文件如何下载，您给出的链接有权限设置，不能直接下载，使用函数dataset.prepare_word2vec()如何生成呢？

**Comment by tanyue2019** [comment]
你好，我想麻烦问一下您，您是用作者要求的pytorch==1.3.0,torch_geometric==1.3.2进行训练的吗？现在这两个版本已经没有了，我不太知道如何能够配好正确的环境。期待您的回复，谢谢！

**Comment by LoveAnneke** [comment]
> 您好，我想请问一下word2vec_redial.npy文件如何下载，您给出的链接有权限设置，不能直接下载，使用函数dataset.prepare_word2vec()如何生成呢？

你好，请问你一下，这个代码你跑出来了吗？
