### ISSUE TITLE
MIM计算问题

### ISSUE THREAD

**Issue by LeeeeoLiu** [Lancelot39/KGSF#6]
Hi~ o(*￣▽￣*)ブ，请问论文中，下面这个公式的期望是如何计算的？
![image](https://user-images.githubusercontent.com/11703395/113137327-00503a80-9257-11eb-99d1-67955bec9da5.png)

我在代码里发现了下面的实现，感觉跟论文中描述的方式不太一样？（不知道是不是我看漏了
https://github.com/Lancelot39/KGSF/blob/a10c02cf31dd70d55e972c9ad046df16886f88e1/model.py#L315-L326

**Comment by Irreel** [comment]
MIM这一部分我也有同样的疑问 请问您问题解决了吗？

**Comment by dayuyang1999** [comment]
我也有同样的疑问。还有为何 info_loss_con被注释掉了呢？

**Comment by Yang-bug-star** [comment]
我也是，根本就不是MIM对应实现嘛，不知具体代码是在哪部分，希望作者说明一下

**Comment by LeeeeoLiu** [comment]
之前给作者发邮件，作者回复 MIM实现和这种实现的结果差不多，这种实现更简单，所以选择了这种实现

**Comment by LoveAnneke** [comment]
> 之前给作者发邮件，作者回复 MIM实现和这种实现的结果差不多，这种实现更简单，所以选择了这种实现

请问你跑出来这个代码了吗？我第二步跑了十几个小时还是不出结果

**Comment by LoveAnneke** [comment]
> 

请问这个程序你复现了吗？

**Comment by Yang-bug-star** [comment]
不好意思，我跑的时候有许多错误还没有克服，主要是看源码学习，找不到MIM模块，非常感谢您的回答，但我想知道这种新的实现是使用了什么数学原理，还是互信息最大化吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lancelot39/KGSF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 下午5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lancelot39/KGSF] MIM计算问题 (#6)





  
之前给作者发邮件，作者回复 MIM实现和这种实现的结果差不多，这种实现更简单，所以选择了这种实现
  
请问你跑出来这个代码了吗？我第二步跑了十几个小时还是不出结果

**Comment by Yang-bug-star** [comment]
非常感谢您的回答，但我想知道这种新的实现是使用了什么数学原理，还是互信息最大化吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lancelot39/KGSF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lancelot39/KGSF] MIM计算问题 (#6)





 
Closed #6 as completed.

**Comment by Irreel** [comment]
我在去年和别人一起复现了 达到了paper的结果 MIM部份的代码和paper写的有出入但是不影响跑出来结果 

> MIM这一部分我也有同样的疑问 请问您问题解决了吗？

**Comment by LoveAnneke** [comment]
请问，你第二步（python run.py --is_finetune True）训练跑了大概多久？是第一步运行完成后，直接命令行执行这个语句吗？
你还记得吗？




溈伱‰伤心&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lancelot39/KGSF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 下午5:12
***@***.***&gt;;
抄送:&nbsp;"溈伱‰伤心 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lancelot39/KGSF] MIM计算问题 (#6)





 
我在去年和别人一起复现了 达到了paper的结果 MIM部份的代码和paper写的有出入但是不影响跑出来结果
  
MIM这一部分我也有同样的疑问 请问您问题解决了吗？

**Comment by Irreel** [comment]
> 请问，你第二步（python run.py --is_finetune True）训练跑了大概多久？是第一步运行完成后，直接命令行执行这个语句吗？ 你还记得吗？ 溈伱‰伤心&nbsp; ***@***.*** &nbsp;
> […](#)

包括finetuning我们在一张卡上跑了13个小时左右 不太记得配置了（2080？）

**Comment by LoveAnneke** [comment]
那你还有跑好的代码吗？我跑第二步跑了大概17个小时都没跑出来




溈伱‰伤心&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lancelot39/KGSF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 下午5:29
***@***.***&gt;;
抄送:&nbsp;"溈伱‰伤心 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lancelot39/KGSF] MIM计算问题 (#6)





  
请问，你第二步（python run.py --is_finetune True）训练跑了大概多久？是第一步运行完成后，直接命令行执行这个语句吗？ 你还记得吗？ 溈伱‰伤心&nbsp; @.*** &nbsp;
 …
  
包括finetuning我们在一张卡上跑了13个小时左右 不太记得配置了（2080？）

**Comment by Yang-bug-star** [comment]
> 之前给作者发邮件，作者回复 MIM实现和这种实现的结果差不多，这种实现更简单，所以选择了这种实现

请问代码里这种新的实现是使用了什么数学原理

**Comment by Yang-bug-star** [comment]
> 我在去年和别人一起复现了 达到了paper的结果 MIM部份的代码和paper写的有出入但是不影响跑出来结果
> 
> > MIM这一部分我也有同样的疑问 请问您问题解决了吗？

您好，想问一下max-r-length和max-c-length表示什么意思呢

**Comment by Yang-bug-star** [comment]
> 那你还有跑好的代码吗？我跑第二步跑了大概17个小时都没跑出来 溈伱‰伤心&nbsp; ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Lancelot39/KGSF" ***@***.***&gt;; 发送时间:&nbsp;2022年11月9日(星期三) 下午5:29 ***@***.***&gt;; 抄送:&nbsp;"溈伱‰伤心 ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Lancelot39/KGSF] MIM计算问题 (#6) 请问，你第二步（python run.py --is_finetune True）训练跑了大概多久？是第一步运行完成后，直接命令行执行这个语句吗？ 你还记得吗？ 溈伱‰伤心&nbsp; @.*** &nbsp; … 包括finetuning我们在一张卡上跑了13个小时左右 不太记得配置了（2080？） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请问第一步运行python run.py遇到a view of a leaf Variable that requires grad is being used in an in-place operation错误如何解决
